### ISSUE TITLE
使用uniapp开发，在真机上main.css中定义的css变量失效

### ISSUE THREAD

**Issue by llj0028** [weilanwl/ColorUI#130]
![db4f35b56f0f356df5a9862b734e53f](https://user-images.githubusercontent.com/32165861/57512203-a92cde00-733d-11e9-912b-b557710339c3.jpg)

**Comment by mokurofuzo** [comment]
同样的问题，和安卓版本有关系，安卓8.0，api26以上都没问题，安卓5.1以下好像都是这样

**Comment by kenny1002** [comment]
这个问题修复没有

**Comment by weilanwl** [comment]
这个是var的兼容问题 大版本改动将改用less 下个小版本会去掉var
