### ISSUE TITLE
大家有没有遇到在页面中使用echart画图后，图将导航栏遮挡住的问题！

### ISSUE THREAD

**Issue by liugezhou** [weilanwl/ColorUI#137]
问下大家，如题！echarts图将导航栏给遮挡住了！

**Comment by liugezhou** [comment]
看来是没有。。。

**Comment by fairyly** [comment]
> 问下大家，如题！echarts图将导航栏给遮挡住了！

canvas 原生组件层级高于其他非原生组件,

- [native-component](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)

**Comment by NameLi** [comment]
导航栏用 cover-view 重写，且必须放在 echars 组件后面（尽量放页面最后面）

**Comment by 86100488z** [comment]
如果是在h5环境下，echarts的层级非常高  需要修改z-index

**Comment by liliukuan** [comment]
遇到了，还没解决。

**Comment by liliukuan** [comment]
> 导航栏用 cover-view 重写，且必须放在 echars 组件后面（尽量放页面最后面）

重写了。但是在手机上直接没了导航，请问你怎么解决的

**Comment by jsuper1980** [comment]
用F2，遇到的问题
