### ISSUE TITLE
.bg-green.light 这个CSS background-color。微信小程序没办法识别

### ISSUE THREAD

**Issue by AdrianaWarlock** [weilanwl/ColorUI#162]
![image](https://user-images.githubusercontent.com/47598373/60397534-c5e8d380-9b80-11e9-9951-42b7c60c9102.png)

**Comment by grath10** [comment]
这应该是多了两个字符吧

**Comment by AdrianaWarlock** [comment]
> 这应该是多了两个字符吧

..嗯，小程序里面有个组件不支持这种写法..  h5 app 里是支持的
