### ISSUE TITLE
写的什么jb

### ISSUE THREAD

**Issue by CheRat** [weilanwl/ColorUI#165]

**Comment by ThisModernLife** [comment]
看到您发的最后一条issue，我忍不住在下面打出回复，关闭该issue出来，发现您在前面居然还有发布的issue，先在这里道个歉，没忍住又来回复您了

现在有句话叫做“你行你上啊，不行别bb”
觉得别人不行，那就您来写一个更好的让大家看看，这样显得您有点水平
别在电脑背后当个网络喷，键盘侠
再次重申这是个开源项目
对于开源项目，好的方面我们可以借鉴，有差劲的地方我们可以提出改进建议，而不是一昧的批评或者严重点像您这样出口成章

既然用了别人的东西那么请您至少表示一点谢意
一没感谢
二没贡献
三issue影响大家心情
恕我直言，属实弟弟

**Comment by kangkang66** [comment]
傻逼玩意
