### ISSUE TITLE
issue里面全他妈提bug的 你特么回复了 ？ 你碧莲呢 ？ 全他妈在朋友圈里面了

### ISSUE THREAD

**Issue by CheRat** [weilanwl/ColorUI#168]

**Comment by wuchunkit** [comment]
1：第一这是个开源免费的项目，没收你钱。唧唧歪歪什么？
2：你以为作者就靠这个24小时不停改BUG来活？人家不用赚钱？不用社交？
3：用人家的东西感谢之意都没，还爆粗。您碧莲呢 ？

**Comment by ThisModernLife** [comment]
开源无人权？
一没收你钱，
二没求你用，
三人家爱发朋友圈就发朋友圈，想改bug就改bug，那是别人的自由
怎么用别人东西还给自己整出优越感来了呢
我看您是不知火舞的弟弟吧
不知好歹
不知廉耻
不知天高地厚 
不知斤两几何
抑或者宁是
不知悔改？
最后再接个不知者无罪？

**Comment by crabfrommars** [comment]
你可真是个弟弟 自己一点本事没有 舔着脸用别人免费开源的产品 还要在这喷粪闹别扭 活该一事无成

**Comment by ddzy** [comment]
从`owner`的角度讲, 楼主的话确实说过了.

但是站在`使用者`的立场, 既然开源了产品, 就应该负责上心,

骗了一波炮, 就不管了, 那可不行:shit:
