### ISSUE TITLE
就一个问题

### ISSUE THREAD

**Issue by yautah** [weilanwl/ColorUI#18]
首先做的很不错
其次，这套wxss样式只能用在page层级
在自定义组件的wxml中基本无法使用
自定义组件的wxss中诸多的选择器限制是个麻烦

**Comment by weilanwl** [comment]
微信官方限制，page层样式传不到组件，不然2.0就做做封装组件了

**Comment by yautah** [comment]
我去。。。
刚才仔细看了文档
`/* 组件 custom-component.js */
Component({
  options: {
    addGlobalClass: true,
  }
})`

这样就可以使用全局样式了
感觉发现了新世界

**Comment by zenghao0219** [comment]
> 我去。。。
> 刚才仔细看了文档
> `/* 组件 custom-component.js */ Component({ options: { addGlobalClass: true, } })`
> 
> 这样就可以使用全局样式了
> 感觉发现了新世界

我怎么没看到~求地址!!!

**Comment by zenghao0219** [comment]
> 我去。。。
> 刚才仔细看了文档
> `/* 组件 custom-component.js */ Component({ options: { addGlobalClass: true, } })`
> 
> 这样就可以使用全局样式了
> 感觉发现了新世界
找到了 感谢!
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html
