### ISSUE TITLE
Demo 文件夹导入工程后，样式混乱

### ISSUE THREAD

**Issue by gaollg** [weilanwl/ColorUI#21]
![image](https://user-images.githubusercontent.com/2359462/50821547-6b598200-136a-11e9-8eae-9bd6c1eef588.png)
直接导入 Demo 样式如上图所示，代码版本地址：https://github.com/weilanwl/ColorUI/tree/70cf39ea1c04057043aa7dd09d0c52e51bce2012

**Comment by weilanwl** [comment]
无复现
