### ISSUE TITLE
建议移除标签名选择器，以避污染组件样式

### ISSUE THREAD

**Issue by gaollg** [weilanwl/ColorUI#22]
![image](https://user-images.githubusercontent.com/2359462/50839113-98258d80-139a-11e9-8a49-8c3bb37976cb.png)
如截图所示，colorUI 的全局样式，已经影响到自定义组件样式，尤其还有后缀有 !important 的属性。详见[微信小程序自定义组件 - 使组件接受全局样式](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E4%BD%BF%E7%BB%84%E4%BB%B6%E6%8E%A5%E5%8F%97%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F)。

### 建议处理方式：

1. 借鉴 [Vant](https://youzan.github.io/vant-weapp/#/button) 的做法，例将 button 前缀字符为 van-button。
2. 弃用标签名选择器，改用 class 表示，缺点是 Html 标签变长了一些。

**Comment by gaollg** [comment]
![image](https://user-images.githubusercontent.com/2359462/50840887-762e0a00-139e-11e9-8587-f7654049aca1.png)
再补充一个，class*="" 也会破坏组件的内部结构。

**Comment by weilanwl** [comment]
colorui 不考虑兼容其他组件库，作为样式类的库，也没有考虑做出小程序自定义组件，

**Comment by weilanwl** [comment]
关于是否抛弃标签名选择器，有在考虑，近期不会变动。感谢支持。
