### ISSUE TITLE
步骤条，步骤内容长度不一样时排版错乱

### ISSUE THREAD

**Issue by RBANNINGS** [weilanwl/ColorUI#245]
![image](https://user-images.githubusercontent.com/31715050/70202212-f9ddab80-1753-11ea-833e-d2be0aa20faf.png)
![image](https://user-images.githubusercontent.com/31715050/70202225-03671380-1754-11ea-80ec-54b40ca3eae8.png)

**Comment by RBANNINGS** [comment]
现在就暂时固定了长度，然后text-overflow:ellipsis了。

**Comment by Greenplumwine** [comment]
改一下他的main.css 将上面的文本设置长度，文字居中，自动换行就可以了

**Comment by Greenplumwine** [comment]
自动换行用word-break:break-all

**Comment by RBANNINGS** [comment]
谢谢了！然后改用
![image](https://user-images.githubusercontent.com/31715050/77887111-9811f600-729c-11ea-9a61-aa96d7a84bc7.png) 这种方式展现也可以。
