### ISSUE TITLE
微信小程序里顶部“返回”按钮建议增加自定义点击响应

### ISSUE THREAD

**Issue by KuoKongQingYun** [weilanwl/ColorUI#259]
现在遇到分享场景，分享出去的页面顶部显示“返回”，但是实际上这个“返回”点不动，因为通过分享进来的用户没法后退，我虽然可以通过代码控制它不显示，但更好的方案应该是 替换为“首页”按钮，然后自定义点击事件处理，让用户点击以后回到首页，而不是默认的后退

**Comment by KuoKongQingYun** [comment]
自己修改了cu-custom解决了

**Comment by gclsoft** [comment]
@KuoKongQingYun 怎么改的

**Comment by KuoKongQingYun** [comment]
> @KuoKongQingYun 怎么改的

修改ColorUI的源码，把点击事件的事件函数改了
