### ISSUE TITLE
colorui.wxss里全是!important

### ISSUE THREAD

**Issue by sweetwong** [weilanwl/ColorUI#28]
我自己想修改一些东西，改了半天发现没用，后面发现有!important，以致于我要再写个!important覆盖才行，不能按照CSS正常的层叠的优先级，然后我在colorui.wxss里搜索!important关键字，发现匹配166个，就是说基本全篇都是，能不能把这些去掉呢？

https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity
里面也说了：“Never use !important when you're writing a plugin/mashup.”
你们作为第三方组件库，应该要避免这种情况吧？

**Comment by weilanwl** [comment]
关于属性的优先级，后续会优化
