### ISSUE TITLE
css样式及图标未生效

### ISSUE THREAD

**Issue by hyfdemo** [weilanwl/ColorUI#31]
编辑器里一切正常；
![image](https://user-images.githubusercontent.com/23278722/52159594-7392ac00-26e1-11e9-9705-5cb05a34acd4.png)
但手机预览就缺少样式及图标，这是怎么回事？
![image](https://user-images.githubusercontent.com/23278722/52159610-a89efe80-26e1-11e9-8f4d-e98c292404f1.png)

**Comment by hyfdemo** [comment]
![image](https://user-images.githubusercontent.com/23278722/52159651-47c3f600-26e2-11e9-9b4b-982559a760ff.png)

**Comment by weilanwl** [comment]
map组件上请使用用cover-view 组件，cover-view组件的限制，请阅读官方文档
[https://developers.weixin.qq.com/miniprogram/dev/component/cover-view.html](https://developers.weixin.qq.com/miniprogram/dev/component/cover-view.html)
