### ISSUE TITLE
card-swiper卡片式轮播左边的图会消失

### ISSUE THREAD

**Issue by YuechuWU1129** [weilanwl/ColorUI#341]
card-swiper卡片式轮播滚动时，左边的图会马上消失
![IMG_8913](https://user-images.githubusercontent.com/59052328/162606842-d1db4f01-04a8-495a-a6a0-f0d8fac338ab.PNG)

**Comment by JhihYangWu** [comment]
小技巧，添加previous-margin="1rpx"到swiper里面

<img width="227" alt="image" src="https://user-images.githubusercontent.com/32950648/169161959-647be34d-9ab9-4aec-8f2b-9d707d8a503a.png">

**Comment by YuechuWU1129** [comment]
谢谢，试了很多方法都不行，加上previous-margin="1rpx"就解决了！
