### ISSUE TITLE
官网开发文档打不开了，问下还会维护吗？

### ISSUE THREAD

**Issue by chennianjie** [weilanwl/ColorUI#344]
[www.color-ui.com/](https://www.color-ui.com/)

**Comment by LiaoShuaiAcount** [comment]
打开了吗？https://www.color-ui.com/ 我还是打不开....

**Comment by almas-x** [comment]
可以打开的，只是ssl证书过期了而已

**Comment by chennianjie** [comment]
打不开，看起来像域名过期了，我试了http也打不开

**Comment by F57** [comment]
域名掉备案了

**Comment by liushuiruoxuan** [comment]
官网什么时候可以打开呢，有在解决嘛

**Comment by LTAND** [comment]
可以用github的静态页面部署或者语雀

**Comment by lihe6666** [comment]
凉凉了，散了散了

**Comment by VolnaTime** [comment]
这个好像开始维护 https://one.x-artspace.cn/ColorUI-GA-Docs/#/
