### ISSUE TITLE
timeline的线在iphone X下消失了

### ISSUE THREAD

**Issue by ashengtx** [weilanwl/ColorUI#42]
![timeline1](https://user-images.githubusercontent.com/7556816/53285332-4003e880-379a-11e9-9d47-8afe84785b34.png)
![timeline2](https://user-images.githubusercontent.com/7556816/53285334-41cdac00-379a-11e9-974e-1b2a6d55d069.png)

**Comment by weilanwl** [comment]
真机显示是否正常？

**Comment by ashengtx** [comment]
> 真机显示是否正常？

没有真机，不知道呀，/捂脸

**Comment by show-hand** [comment]
> > 真机显示是否正常？
> 
> 没有真机，不知道呀，/捂脸

真机测试显示正常
