### ISSUE TITLE
小程序-全屏抽屉

### ISSUE THREAD

**Issue by weijiyang** [weilanwl/ColorUI#48]
界面错乱

**Comment by LeachZhou** [comment]
这种问题你让别人怎么处理，好歹 页面截图 机型 浏览器 环境等等方便你要说一下吧

**Comment by weilanwl** [comment]
已收到哟，初步判断为特有机型小程序API输出错误数据。目前大部分机型是正常的。

**Comment by weijiyang** [comment]
sorry哈   没说清楚 
iphone8 plus  11.4.1版本 

![5acee049c21ae18b123e1973b264d8b8](https://user-images.githubusercontent.com/23150533/53628930-4a652d00-3c47-11e9-8962-f3726c6bfc94.png)
![37f5e4dfbbf4dcedb2b134e0fac901a4](https://user-images.githubusercontent.com/23150533/53628938-4f29e100-3c47-11e9-879c-9b1b609a3ace.png)

**Comment by weilanwl** [comment]
初步判断为基础库的问题，更新到最新版是否复现？

**Comment by weijiyang** [comment]
之前版本微信扫码 提示更新版本
现在更新微信版本到 7.0.3后  
索引界面正常
全局抽屉界面样式依然错乱
