### ISSUE TITLE
模态窗口的侧边抽屉高度不对

### ISSUE THREAD

**Issue by JokerLoLgrey** [weilanwl/ColorUI#50]
模态窗口的侧边抽屉高度不对，忘记减掉顶部导航栏的高度（并且好多底部的功能栏没有兼容iPhoneX，iPhoneX底部有34px的安全区）
![img_0841](https://user-images.githubusercontent.com/33446705/53684016-0a837000-3d43-11e9-9a8c-ffa612f7af03.PNG)
![img_0842](https://user-images.githubusercontent.com/33446705/53684042-56ceb000-3d43-11e9-9e95-5496aa93a5da.PNG)

**Comment by weilanwl** [comment]
好的，已收到
