### ISSUE TITLE
封装成tabbar,结果点9下就卡死了，所有菜单都不能动，求解~~~

### ISSUE THREAD

**Issue by robber2000** [weilanwl/ColorUI#57]
封装成tabbar,结果点9下就卡死了，所有菜单都不能动，求解~~~ 

<view class="cu-bar tabbar foot solid-bottom margin-top bg-gradual-blue">
  
    <view class="action text-white" bindtap="selectMenu">
      <view class='icon-similar' ></view>菜谱
    </view>
   
    <view class="action text-white" bindtap="selectCart">
      <view class='icon-cart'>
        <view class='cu-tag badge'>99</view>
      </view>
      点餐单
    </view>
    <view class="action text-white" bindtap="selectCenter">
      <view class='icon-my'>
        <view class='cu-tag badge'></view>
      </view>
      我的
    </view>
  </view>

// components/demo/index.js
Component({
    /**
     * 组件的属性列表
     */
    properties: {
        name: {
            type: String,
            value: ''
        }
    },

    /**
     * 组件的初始数据
     */
    data: {
        type: "组件"
    },
    options: {
        addGlobalClass: true,
    },
    /**
     * 组件的方法列表
     */
    methods: {
        selectMenu: function () {
            
            wx.navigateTo({
                url:"../index/index"
            })
        },
        selectCart: function () {

            wx.navigateTo({
                url: "../cart/cart"
            })
        },
        selectCenter: function () {

            wx.navigateTo({
                url: "../center/center"
            })
        },
    }
})

**Comment by TLingC** [comment]
tabbar不要用navigateTo。
navigateTo相当于你每次点击都打开一个新窗口，而且小程序有限制页面栈最多10层（https://developers.weixin.qq.com/miniprogram/dev/api/wx.navigateTo.html）。

**Comment by robber2000** [comment]
> 
> 
> tabbar不要用navigateTo。
> navigateTo相当于你每次点击都打开一个新窗口，而且小程序有限制页面栈最多10层（[https://developers.weixin.qq.com/miniprogram/dev/api/wx.navigateTo.html）。](https://developers.weixin.qq.com/miniprogram/dev/api/wx.navigateTo.html%EF%BC%89%E3%80%82)

感谢回复！明白了，，
