### ISSUE TITLE
IOS真机调试崩溃

### ISSUE THREAD

**Issue by fatelesscn** [weilanwl/ColorUI#58]
大概看了下貌似是getMenuButtonBoundingClientRect的问题，请大佬帮忙查下问题原因。
而且现在的DEMO小程序里的TOPBAR用IOS看也是错位的。

**Comment by fatelesscn** [comment]
![image](https://user-images.githubusercontent.com/16491120/53930083-f3d67380-40ca-11e9-9a33-6b0a6b115c7c.png)
![image](https://user-images.githubusercontent.com/16491120/53930090-f9cc5480-40ca-11e9-9227-1a4fec2d9d56.png)

**Comment by weilanwl** [comment]
亲，建议去官方社区提交反馈呢

**Comment by fatelesscn** [comment]
> 亲，建议去官方社区提交反馈呢

我就想知道我是不是个例- -

**Comment by pygroos** [comment]
> > 亲，建议去官方社区提交反馈呢
> 
> 我就想知道我是不是个例- -

我也遇到这个问题 真机调试崩溃 等官方修复吧
https://developers.weixin.qq.com/community/develop/doc/0006cc9c1f04f817b8b709ec351000
