### ISSUE TITLE
XR上 自定义导航栏出现浮动

### ISSUE THREAD

**Issue by TuKun33** [weilanwl/ColorUI#65]
问题是出在用户那边，我也没手机 试不出来

多的情况问不到，那边也只会甩问题

就是这个样子了
![](https://mmbiz.qpic.cn/mmbiz_jpg/2BRj24JibAF3m4W0R4440afwApF3S6AAbnGRaLqdRakWOvK0QZbb2gDmOaZYDDjrRTPicnVXVKzibQXWgh0Dh8mEQ/0?wx_fmt=jpeg)

--

正常应该这样
![](https://mmbiz.qpic.cn/mmbiz_jpg/2BRj24JibAF3m4W0R4440afwApF3S6AAbRC9vHvjSdib8JvYILQ0v8kIxict9EichQBNgyvQhjVgcN8ib8CbZpYoLLg/0?wx_fmt=jpeg)

**Comment by weilanwl** [comment]
可以贴下具体的代码或者写个代码片段，我这边好复习问题
