### ISSUE TITLE
Bug！弹出提示框会时当提示框下有textarea时，textarea的placeholder属性值描述会覆盖model，导致bug

### ISSUE THREAD

**Issue by aaronuu** [weilanwl/ColorUI#72]
Bug！弹出提示框model时当提示框下有textarea时，textarea的placeholder属性值描述会覆盖model，导致bug 图层问题 导致model无法操作

**Comment by weilanwl** [comment]
新版本有优化，可以在弹框的时候增加hidden属性使其隐藏

**Comment by aaronuu** [comment]
谢谢
