### ISSUE TITLE
圆角列表底部为input输入框时，圆角无效

### ISSUE THREAD

**Issue by SilverLeaves** [weilanwl/ColorUI#80]
![图片](https://user-images.githubusercontent.com/31165554/55375712-c5b84800-553f-11e9-9d1d-3c3a4ae2c295.png)

**Comment by SilverLeaves** [comment]
必须额外加
```
style="border-bottom-left-radius: 10px;border-bottom-right-radius: 10px;"
```

**Comment by weilanwl** [comment]
表单叠加列表的话，子元素不建议直接使用原生表单组件，建议用view标签包裹
