### ISSUE TITLE
做的非常不错

### ISSUE THREAD

**Issue by JHeLiu** [weilanwl/ColorUI#9]
建议
1、出一个文档
2、弹框的比较马虎，需要细节化一下。
3、希望能类似于PC一样 有一个公共核心 css（wxss）库，
我看过很多开源的UI框架，都喜欢写成一个一个组件，可能很多时候 别人用不着这些组件，他们需要一个核心的样式库而已。

总体来说，非常棒。 出个文档就很好了、

**Comment by nyrf** [comment]
同感，希望出个文档，

**Comment by weilanwl** [comment]
版本升级中 文档后面再出

**Comment by realso** [comment]
找了这么多，你的组件是最漂亮，最流畅的。有vue组件版本吗？

**Comment by distupid** [comment]
翻了一圈早已有人666 哈哈 确实耳目一新 ，希望早点出组件，可以参考某赞的van*
